# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: N2ZiYWU3NjcxNjk4ZjA4Y2I1MTEzYzA3NGZmNzUwNTgwMTNkNTIyODYxYjI3MzFmYWE4M2FjZDUwNGMwYzYzZmQ4ODZhZGJmMGFkM2QxZDBhMDQ5YjM5ZThkZTY1MDU4OWVmNzM2Zjg5NzMzOTFkMWZmMzNhN2M5ZTE2ODUzZWU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
