# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MGNkN2FiNTI4ZGVhODEzNTZmOTJlN2ZhZTQxYjVhNGQwY2E3NTgxZmI4ZTNkMzNjMjJiYTgwNjU2MWNjMDNjZTgwODQ1ZGEwNjAyZDIxNDFkMzAzZGYyMGNiOTg2ZWE1ZmFhYTA4OWFhMDlkODhlNzljYjE5ODc0YjNjMWZjOGY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
